[![Node CI](https://github.com/naddison36/sol2uml/actions/workflows/nodejs.yml/badge.svg?branch=etherscan-multifile-fix&event=pull_request_target)](https://github.com/naddison36/sol2uml/actions/workflows/nodejs.yml)

on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        node-version: [12.x, 14.x, 15.x]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.platform }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test
      env:
        DEBUG: sol2uml
        CI: true
